### ISSUE TITLE
Complex html list extraction to xpath

### ISSUE THREAD

**Issue by trompx** [ispras/dedoc#291]
Hello, thanks for creating dedoc. I am not sure of its complete capabilities. Does it allow to extract list of complex elements from html? Like, detecting patterns in the DOM structure and **extract xpath** of list of elements. For example, search results which are composed of multiples tags.

**Comment by oksidgy** [comment]
No, dedoc cannot extract xpath from html format.  But you can write own html-handler (your reader) with this functionality and do pull-request. You can read about readers here (https://dedoc.readthedocs.io/en/latest/modules/readers.html)

**Comment by NastyBoget** [comment]
The instruction how to add your own reader to `dedoc` can be found [here](https://dedoc.readthedocs.io/en/latest/tutorials/add_new_doc_type.html)
