### ISSUE TITLE
Обучение собственных моделей 

### ISSUE THREAD

**Issue by ValiullinAlbert** [ispras/dedoc#404]
Подскажите, пожалуйста, как можно обучить собственные модели для классификации параграфов и строк и как подготовить данные для обучения?

**Comment by NastyBoget** [comment]
Добавили туториал в новой версии https://dedoc.readthedocs.io/en/latest/tutorials/add_new_structure_type.html

**Comment by ValiullinAlbert** [comment]
Спасибо!
