### ISSUE TITLE
LLM compatible json

### ISSUE THREAD

**Issue by arslan1510** [ispras/dedoc#429]
Heys guys, great stuff you have here, i just wanted to know, that is there any way to feed the parsed output to llm? would need to make chunks which doesnt exceed specific size and have this sections like llmsherpa?

**Comment by NastyBoget** [comment]
Hello! We are planning to make something like that for `langchain` (https://python.langchain.com/docs), this library also simplifies work with LLM. In the future, we want to implement our custom `Document Loader` (https://python.langchain.com/docs/modules/data_connection/document_loaders/) and then you can use some `Text Splitter` (https://python.langchain.com/docs/modules/data_connection/document_transformers/) for making chunks of fixed length.

Now dedoc doesn't support making chunks, it supports only making `TreeNode` for each paragraph of the text, but its length isn't limited by specific size.

**Comment by tejeshbhalla** [comment]
> Ahh cool, will for sure contribute to this whenever i can, closing this issue and thanks for replying.

Where's your contribution?

**Comment by NastyBoget** [comment]
We are in the process of writing code for `langchain` (https://python.langchain.com/docs), it will be there if they approve our pull request (we haven't done PR yet)
