### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by Scoutink** [ispras/dedoc#437]
Great work!
Certainly the best I came across and I've been searching...
Can't you make it also extract images from the pdfs? I gave it a complex pdf with text tables and images and it was impressive beside missing on extracting the images.

**Comment by NastyBoget** [comment]
Thank you for your feedback! 
Extracting images from PDFs should work with parameter `with_attachments="true"`.
You can get more details in the documentation:
1. If you use dedoc API, [parameters description](https://dedoc.readthedocs.io/en/latest/dedoc_api_usage/api.html#id1) and [return format description](https://dedoc.readthedocs.io/en/latest/dedoc_api_usage/return_format.html#example-with-attachments) may help.
2. If you use dedoc library, [this page](https://dedoc.readthedocs.io/en/latest/parameters/attachments_handling.html) can be useful.

Feel free to ask any questions if something doesn't work properly.

**Comment by Scoutink** [comment]
@NastyBoget Thank you for the feedback. For some reason it is not working for me. Not sure if this is appropriate to ask here, but are you open to help me using this in a project I am working on (for a fee we can discuss, of course). I may even point you to another repo with an interesting approach to this same field that may improve the results.

**Comment by NastyBoget** [comment]
If you have an example PDF file, I can try to process it myself. Maybe we have a bug on some specific cases.

**Comment by Scoutink** [comment]
[sample.pdf](https://github.com/ispras/dedoc/files/15233244/sample.pdf)
here is a sample I downloaded from the web.

**Comment by NastyBoget** [comment]
Did you try to set `return_format` into `json`? In this case, images are enlisted in `attachments` field (tried it myself). Currently, we don't show attachments in the HTML representation (it will be added in the next version of dedoc).
By the way, I would recommend to work with attached images using dedoc library (not API), or use `base64_encode` parameter for storing images content in metadata.

**Comment by Scoutink** [comment]
That makes sense, and very helpful. Thanks.
