### ISSUE TITLE
Ошибка в чтении файла

### ISSUE THREAD

**Issue by ValiullinAlbert** [ispras/dedoc#478]
При чтении прикрепленного файла происходит ошибка 
[1 — копия.docx](https://github.com/user-attachments/files/16493610/1.docx)

```
reader = DocxReader(config={})
filepath = "1 — копия.docx"
document1 = reader.read(filepath, parameters={"with_attachments": "false", "need_header_footer_analysis": "True"})
```

**Comment by NastyBoget** [comment]
Баг воспроизвелся, постараемся исправить в ближайшее время

**Comment by alexander1999-hub** [comment]
Мы исправили ошибку при обработке этого файла. Дело в том, что он не совсем корректный и с нашей стороны код не был рассчитан на это.

Код с исправлением этого бага уже есть в ветке develop. С ближайшим релизом он станет доступен в библиотеке и в ветке master

**Comment by ValiullinAlbert** [comment]
Подскажите, пожалуйста, в чем некорректность файла была, и какие файлы вообще лучше подавать для системы?

**Comment by NastyBoget** [comment]
Во внутреннем представлении (xml коде) таблицы указано, что ячейки в двух строках должны быть смёржены по вертикали, но в редакторе они отображаются в двух разных рядах. Согласно внутреннему представлению смёржить их невозможно: колспаны ячеек сверху - 2,2,2,1; снизу - 1,2,2,2 (колспаны означают мерж ячеек по горизонтали).  
Вообщя говоря, для системы можно подавать любые файлы (если речь идет про docx), которые открываются в текстовом редакторе без ошибок. Если наша система с таким не справляется, то это баг

**Comment by ValiullinAlbert** [comment]
Спасибо!
