### ISSUE TITLE
Ошибка в определении bold

### ISSUE THREAD

**Issue by ValiullinAlbert** [ispras/dedoc#479]
При прочтении следующего файла
[2 — копия.docx](https://github.com/user-attachments/files/16495055/2.docx)

```
document1 = reader.read("2 — копия.docx", parameters={"with_attachments": "false", "need_header_footer_analysis": "True"})
print(document1.lines)
```

При прочтении второй и третьей строки, они отображается как bold:
```
print(document1.lines[2].annotations[-1].to_api_schema())
print(document1.lines[3].annotations[-1].to_api_schema())
```

Хотя они не является жирными в документе

**Comment by NastyBoget** [comment]
Баг воспроизвелся, постараемся поправить

**Comment by NastyBoget** [comment]
Поправлено в версии `dedoc==2.3.1`
