### ISSUE TITLE
Практические кейсы, для примеров блокнотов.

### ISSUE THREAD

**Issue by nikitaCodeSave** [ispras/dedoc#484]
Dedoc  - интересная и комплексная библиотека.
Но порог входа очень высокий.
Пример кейсов, в которых Dedoc  может быть интегрирован.

**Классификация документов**
_Описание кейса:_
В организации есть поток входящих документов от клиентов. Документы предоставляются в следующих форматах:
 ⁃ pdf: машиночитаемый формат и сканы
 ⁃ tiff: сканы
 ⁃ jpeg: сканы
 ⁃ png: сканы
 ⁃ doc, docx: машиночитаемый формат

_Бизнес-задача:_
Классифицировать поток входящих документов по предоставленным классам. 
Например, паспорт, доверенность, учредительные документы, договор и иное.
_ML-задача:_
 1. Получить документ
 2. Распознать формат и тип документа (машиночитаемый формат или скан)
 3. Извлечь текст из документа в структурированном виде (заголовки\ абзацы \ блоки)
 4. Сохранить текст для его дальнейшей классификации иным инструментом
 
![scan](https://github.com/user-attachments/assets/cadb69fb-61a0-4869-a634-f0da4afd3e16)

**Извлечение табличных данных**
_Описание кейса:_
Поток входящих документов с табличными данными. 
Документы предоставляются в следующих форматах:
 ⁃ pdf: сканы
 ⁃ tiff: сканы
 ⁃ jpeg: сканы
 ⁃ png: сканы

_Бизнес-задача:_
Извлечь табличные данные для последующей обработки в табличном виде(.csv).
Например, Отчетности, спецификации, анкеты.
_ML-задача:_
 1. Получить документ
 2. Распознать формат и тип документа (одностраничный или многостраничный)
 3. Извлечь таблицы из документа в структурированном виде (собрать разделенные таблицы на разных листах, отделить таблицы с одного листа, если их несколько)
 4.  Сохранить отдельные таблицы для дальнейшей обработки
 
![image_1](https://github.com/user-attachments/assets/ce366218-48e7-4010-a76c-99547a9cdcab)
![image_2](https://github.com/user-attachments/assets/0caae211-a7fb-4a94-87ba-97d47df7775d)

**Comment by NastyBoget** [comment]
Создали страницу с примерами в Google colab: https://dedoc.readthedocs.io/en/latest/tutorials/notebooks.html
