### ISSUE TITLE
Проблема в нумерации при чтении файла docx

### ISSUE THREAD

**Issue by ValiullinAlbert** [ispras/dedoc#494]
В следующем файле 
[12.docx](https://github.com/user-attachments/files/16965498/12.docx)
 неправильно идет нумерация:

```
from dedoc.readers import DocxReader
reader = DocxReader(config={})
filepath = '12.docx'
document1 = reader.read(filepath, parameters={"with_attachments": "false", "need_header_footer_analysis": "True"})
for line in document1.lines:
    print(line.line)
```

То есть нумерация сдвинута на 1 по сравнению с исходным документом

**Comment by NastyBoget** [comment]
![Screenshot 2024-09-12 at 12 42 38](https://github.com/user-attachments/assets/a2f94941-63c7-4f15-8ee5-c7605df6e909)

Интересно, что быстрый просмотр документа на mac os показывает то же, что выдает Dedoc. Но при открытии файла нумерация меньше на 1. Посмотрим, в чем проблема

**Comment by NastyBoget** [comment]
Поправили в версии `dedoc==2.3`
