### ISSUE TITLE
How can I obtain the line_id of the table and picture?

### ISSUE THREAD

**Issue by Ask-sola** [ispras/dedoc#505]
Hello, please help me.
When I use dedoc to parse a .docx file, I cannot obtain the line_id of the table to match its position in the text.

**Comment by NastyBoget** [comment]
Hello! You can use [TableAnnotation](https://dedoc.readthedocs.io/en/latest/modules/data_structures.html#dedoc.data_structures.TableAnnotation) for this purpose ([AttachAnnotation](https://dedoc.readthedocs.io/en/latest/modules/data_structures.html#dedoc.data_structures.AttachAnnotation) for attached files, e.g. pictures). [Here](https://dedoc.readthedocs.io/en/latest/getting_started/usage.html#document-tables) you can see example of tables linking to the lines of the document.

P.s. for extracting attachments, you'll need to use `"with_attachments":"true"` in the parameters of parsing
